### ISSUE TITLE
update to gd v4.2

### ISSUE THREAD

**Issue by jinsediaoying** [YuriSizov/godot-editor-theme-explorer#10]
in plugin.gd file, line 15	
change
`var godot_theme = get_editor_interface().get_base_control().theme`
to	
`var godot_theme = get_editor_interface().get_editor_theme()`

**Comment by YuriSizov** [comment]
Done in https://github.com/YuriSizov/godot-editor-theme-explorer/commit/c4a3d5ef3a0c73b1cda99725b0446d870a704129. Version 2.1.0 is compatible with Godot 4.2, soon to be available on the asset lib.
