### ISSUE TITLE
Leaks CanvasItem Objects

### ISSUE THREAD

**Issue by Tattomoosa** [YuriSizov/godot-editor-theme-explorer#12]
```
WARNING: 19 RIDs of type "CanvasItem" were leaked.
     at: _free_rids (servers/rendering/renderer_canvas_cull.cpp:2485)
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
     at: cleanup (core/object/object.cpp:2284)
```

Reproducible by cloning this repo but also appeared in my own plugin project when I installed from AssetLib. To reproduce, you have to run Godot from the terminal (or otherwise with console output) to get leaked object output when it exits

**Comment by YuriSizov** [comment]
Hey, thanks for the report. Which version of the engine are you using?

**Comment by Tattomoosa** [comment]
4.3 stable

**Comment by YuriSizov** [comment]
Hey, sorry for the delay. The leak should be fixed by https://github.com/YuriSizov/godot-editor-theme-explorer/commit/dc2cfbc22e4b0b66e777d2c1a4578d71c919f1ae. You can already get the plugin v2.1.1 from GitHub, and I'll push an update to the AssetLib shortly.
